#include "draw_map.h"

#include "../modules/state.h"
#include "../modules/utils.h"

// Define macros that are eventually given by autogenerated headers
#ifndef RESOURCE_ID_MAP_BORDER_COASTLINES
#define RESOURCE_ID_MAP_BORDER_COASTLINES 0
#endif
#ifndef RESOURCE_ID_MAP_TOWNS
#define RESOURCE_ID_MAP_TOWNS 0
#endif
#ifndef RESOURCE_ID_MAP_HIGHWAYS
#define RESOURCE_ID_MAP_HIGHWAYS 0
#endif

#define MAP_LONGITUDE_MIN 11000
#define MAP_LATITUDE_MIN 56000

static GDrawCommandImage* s_draw_command_image_raw_border_coastlines;
static GDrawCommandImage* s_draw_command_image_raw_towns;
static GDrawCommandImage* s_draw_command_image_raw_highways;
static MapZoomLevel s_current_zoom_level;
static const Layer* s_draw_layer;
static GColor s_current_color;

location_t get_map_data_point_location(GPoint point) {
    location_t location = {MAP_LATITUDE_MIN + point.y, MAP_LONGITUDE_MIN + point.x};
    return location;
}

bool draw_map_gdraw_command(GDrawCommand* command, uint32_t index, void* ctx) {
    GDrawCommandType type = gdraw_command_get_type(command);
    if (type == GDrawCommandTypePath) {
        size_t point_count = gdraw_command_get_num_points(command);
        for (size_t point_index = 0; point_index < point_count; point_index++) {
            GPoint point = gdraw_command_get_point(command, point_index);
            location_t location = get_map_data_point_location(point);
            GPoint transformed_point =
                location_to_gpoint(s_draw_layer, &location, s_current_zoom_level);
            gdraw_command_set_point(command, point_index, transformed_point);
        }
        gdraw_command_set_stroke_color(command, s_current_color);
        gdraw_command_set_fill_color(command, GColorClear);
    } else if (type == GDrawCommandTypeCircle) {
        GPoint point = gdraw_command_get_point(command, 0);
        location_t location = get_map_data_point_location(point);
        GPoint transformed_point =
            location_to_gpoint(s_draw_layer, &location, s_current_zoom_level);
        gdraw_command_set_point(command, 0, transformed_point);
        gdraw_command_set_radius(command, 2);
        gdraw_command_set_stroke_color(command, s_current_color);
        gdraw_command_set_fill_color(command, s_current_color);
    }

    gdraw_command_draw(ctx, command);
    return true;
}

void draw_map_component(
    const Layer* layer,
    GContext* ctx,
    GDrawCommandImage* image,
    GColor color,
    MapZoomLevel zoom_level
) {
    // Don't draw if coordinate bounds are not available
    if (state.coordinate_bounds_far.latitude_min == LATITUDE_NA &&
        state.coordinate_bounds_far.longitude_min == LONGITUDE_NA) {
        return;
    }

    s_draw_layer = layer;
    s_current_zoom_level = zoom_level;
    s_current_color = color;

    GDrawCommandImage* command_image = gdraw_command_image_clone(image);
    GDrawCommandList* command_list =
        gdraw_command_image_get_command_list(command_image);
    gdraw_command_list_iterate(command_list, draw_map_gdraw_command, ctx);
    gdraw_command_image_destroy(command_image);
}

void draw_map(const Layer* layer, GContext* ctx, MapZoomLevel zoom_level) {
    draw_map_component(
        layer, ctx, s_draw_command_image_raw_highways, GColorLightGray, zoom_level
    );
    draw_map_component(
        layer, ctx, s_draw_command_image_raw_border_coastlines, GColorBlack, zoom_level
    );
    draw_map_component(
        layer, ctx, s_draw_command_image_raw_towns, GColorBlack, zoom_level
    );
}

void draw_map_init() {
    s_draw_command_image_raw_border_coastlines =
        gdraw_command_image_create_with_resource(RESOURCE_ID_MAP_BORDER_COASTLINES);
    s_draw_command_image_raw_towns =
        gdraw_command_image_create_with_resource(RESOURCE_ID_MAP_TOWNS);
    s_draw_command_image_raw_highways =
        gdraw_command_image_create_with_resource(RESOURCE_ID_MAP_HIGHWAYS);
}

void draw_map_deinit() {
    gdraw_command_image_destroy(s_draw_command_image_raw_border_coastlines);
    gdraw_command_image_destroy(s_draw_command_image_raw_towns);
    gdraw_command_image_destroy(s_draw_command_image_raw_highways);
}
